services:
  openclaw:
    image: 1panel-openclaw:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXTRA_APT_PACKAGES=${EXTRA_APT_PACKAGES:-}
        - INSTALL_PLAYWRIGHT=${INSTALL_PLAYWRIGHT:-false}
    container_name: ${CONTAINER_NAME}
    user: ${RUN_USER:-node}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:18789"
      - "${PANEL_APP_PORT_BRIDGE}:18790"
    environment:
      - HOME=/home/node
      - PLAYWRIGHT_BROWSERS_PATH=/home/node/.cache/ms-playwright
    volumes:
      - ./data/config:/home/node/.openclaw
      - ./data/workspace:/home/node/.openclaw/workspace
      - ./data/playwright:/home/node/.cache/ms-playwright
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
