services:
  openlist:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - './data:/opt/openlist/data'
    #environment:
    #  - HTTP_PROXY=${proxy_url}
    #  - HTTPS_PROXY=${proxy_url}
    #  - no_proxy=*.aliyundrive.com
    image: openlistteam/openlist:latest
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
