services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api-plus:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8317"
    volumes:
      - ./data/config.yaml:/CLIProxyAPI/config.yaml
      - ./data/auths:/root/.cli-proxy-api
      - ./data/logs:/CLIProxyAPI/logs
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
